### ISSUE TITLE
A particular custom install folder on Win 7 x64 renders several components faulty/unusable

### ISSUE THREAD

**Issue by lembitk** [open-eid/windows-installer#1]
When installing Estonian ID-software on Windows 7 Service Pack 1 (64 bit), I've been choosing `c:\Program Files\Estonian ID Card\` (i.e. not the default `Program Files (x86)\`) as the custom install folder within the setup wizard flow of the 64-bit installer. All ID-software used to work with this setup, but after upgrading to the v3.10.3 earlier this year, I started to experience the following issues. 

1. DigiDoc3 Client fails to start with the error message "The application was unable to start correctly (0xc000007b)".
1. DigiDoc3 Crypto fails to start with the error message "The application was unable to start correctly (0xc000007b)".
1. Unable to use digital signing with any browser – Mozilla Firefox, Google Chrome, Internet Explorer –, as the EstEID plugins are missing.

While frustrated, I left this erroneous setup as is for several months. When I tried a clean reinstall with the v3.11.0 now, the issues above persisted. So I tried another clean reinstall, but this time opted for the default install folder `c:\Program Files (x86)\Estonian ID Card\` – and got rid of the issues. When I look now how the 64-bit installer has created the `c:\Program Files\Estonian ID Card\` folder, my earlier custom choice, automatically, I start to feel that here might lie the reason for my interim troubles…

So, while I recognize that this might well be a rare edge case by someone obsessed too much with folder organization (would like to keep software claiming to be x64 in the folder specially designated for x64 by the OS), I'm filing this report nevertheless – hoping it still might prove useful. Please don't mind if not. Thanks.

**Comment by metsma** [comment]
64 bit installer contains 64 and 32 bit components which are installed separate folders ":\Program Files (x86)\Estonian ID Card\ and c:\Program Files\Estonian ID Card\".
Forcing to install same folder overrides some dll which are required correct architecture.
Latest release (3.12.0) this folder selection option is disabled.
