### ISSUE TITLE
DLL in system drive root directory

### ISSUE THREAD

**Issue by virtual-machinist** [open-eid/windows-installer#41]
Due to Linux software package being broken (see https://github.com/open-eid/linux-installer/issues/37) have to use Windows to do basic BDOC/CDOC document handling. :disappointed: 
Couldn't help noticing this rather unusual place to store an application library -
![idemia](https://user-images.githubusercontent.com/1859437/50163376-fa81f580-02e8-11e9-9785-a273acfdcedb.png)
(screenshot taken from a disposable Windows 7 VM)
If it's a system component, shouldn't it be located in `%WinDir%` or `%ProgramFiles%`? Or if it's user-specific, shouldn't it be in `%AppData%`?

**Comment by kristelmerilain** [comment]
Thank you for that information.
This issue will be fixed in our next release.

**Comment by kristelmerilain** [comment]
Fixed in 19.07 release.
